spring:
  application:
    name: user-service
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/gallerydb
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
  zipkin:
    baseUrl: http://localhost:9411/
  sleuth:
    sampler:
      probability: 100

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

movie-service:
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 1000

#movie-service:
#  ribbon:
#    listOfServers: localhost:8085,localhost:8086
#    eureka:
#      enabled: true
